- name: Download Hadoop 
  get_url:
    url: http://apache.cs.utah.edu/hadoop/common/{{HADOOP_VERSION}}/{{HADOOP_VERSION}}.tar.gz
    dest: "{{BASE_HADOOP_FOLDER}}{{HADOOP_VERSION}}.tar.gz"
    timeout: 300

- name: Uncompress hadoop
  unarchive:
    src: "{{BASE_HADOOP_FOLDER}}{{HADOOP_VERSION}}.tar.gz"
    dest: "{{BASE_HADOOP_FOLDER}}"
    remote_src: yes

- name: Remove previous compressed files
  file:
    path: "{{BASE_HADOOP_FOLDER}}{{HADOOP_VERSION}}.tar.gz"
    state: absent

- name: Move Hadoop
  shell: mv "{{BASE_HADOOP_FOLDER}}{{HADOOP_VERSION}}" "{{BASE_HADOOP_FOLDER}}hadoop"

- name: Add bins to path for hadoop user
  lineinfile:
    path: "{{BASE_HADOOP_FOLDER}}.bashrc"
    line: "{{ item }}"
  loop:
    - "export HADOOP_HOME={{BASE_HADOOP_FOLDER}}hadoop"
    - "export PATH=\\${PATH}:\\${HADOOP_HOME}/bin:\\${HADOOP_HOME}/sbin"
    - "export HADOOP_CONF_DIR=\\${HADOOP_HOME}/etc/hadoop"
    - "export LD_LIBRARY_PATH=\\${HADOOP_HOME}/lib/native:\\$LD_LIBRARY_PATH"