- name: Install Java 
  package:
    name: "{{JAVA_VERSION}}"
    state: present

- name: Move Java
  shell: mv /usr/lib/jvm/{{JAVA_VERSION}}* /usr/lib/jvm/{{JAVA_VERSION}}

- name: Remove Java alternatives
  file:
    path: /etc/alternatives/java
    state: absent

- name: Create new Java alternatives
  file:
    src: /usr/lib/jvm/{{JAVA_VERSION}}/jre/bin/java
    dest: /etc/alternatives/java
    state: link

- name: Create Java profile file
  file:
    path: /etc/profile.d/java.sh
    state: touch
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Set up enviroment variables
  lineinfile:
    path: "/etc/profile.d/java.sh"
    line: "{{ item }}"
  loop:
    - export JAVA_HOME=/usr/lib/jvm/{{JAVA_VERSION}}/jre
    - export PATH=${JAVA_HOME}/bin:${PATH}
