- name: Download and uncompress Spark
  unarchive:
    src: https://ftp.cixug.es/apache/spark/{{SPARK_VERSION}}/{{SPARK_VERSION}}-bin-{{SPARK_HADOOP_VERSION}}.tgz
    dest: "/usr/local"
    remote_src: yes

- name: Move Spark
  shell: mv /usr/local/${SPARK_VERSION}-bin-${SPARK_HADOOP_VERSION} {{SPARK_DIR}}

- name: Create Spark profile file
  file:
    path: /etc/profile.d/spark.sh
    state: file

- name: Set up enviroment variables
  lineinfile:
    path: "/etc/profile.d/spark.sh"
    line: "{{ item }}"
  loop:
    - export SPARK_HOME={{SPARK_DIR}}
    - export PATH=${SPARK_HOME}/bin:${PATH}