---
- hosts: all
  gather_facts: no
  become: yes
  become_user: hadoop
  vars_files:
    - vars/main.yml
  tasks:
    - import_tasks: tasks/hadoopCommon.yml

- hosts: masters
  gather_facts: no
  become: yes
  tasks:
    - import_tasks: tasks/hadoopDebuging.yml

- hosts: masters
  gather_facts: no
  vars_files:
    - vars/main.yml
  environment:
    JAVA_HOME: "{{ java_home }}"
  become: yes
  become_user: hadoop
  tasks:
    - import_tasks: tasks/hadoopMaster.yml

- hosts: masters
  gather_facts: no
  become: yes
  tasks:
    - import_tasks: tasks/sparkMaster.yml