---
- hosts: all
  become: yes
  become_user: hadoop

  vars_files:
    - vars/main.yml
  tasks:
    - import_tasks: tasks/main.yml

- hosts: masters
  become: yes
  become_user: hadoop

  tasks:
    - import_tasks: tasks/mymaster.yml