---
- hosts: all
  become: yes
  become_user: hadoop

  vars_files:
    - vars/main.yml
  tasks:
    - import_tasks: tasks/main.yml

- hosts: masters
  become: yes
  tasks:
    - import_tasks:tasks/basicMaster.yml

- hosts: masters
  environment:
    JAVA_HOME: {{ java_home }}
  become: yes
  become_user: hadoop

  tasks:
    - import_tasks: tasks/mymaster.yml