# Define tasks here
- name: Format HDFS
  command: "{{ hadoop_home }}/bin/hdfs namenode -format -force"
  
- name: Start HDFS
  command: "{{ hadoop_home }}/sbin/start-dfs.sh"
  
- name: Start Yarn
  command: nohup {{ hadoop_home }}/sbin/start-yarn.sh &
